### ISSUE TITLE
Evaluate doesn't work in Windows 10

### ISSUE THREAD

**Issue by Onefabis** [richard-roberts/SalientPosesMaya#25]
In windows 10 Evaluate button cause in maya 2018 and 2017 next errors:
Maya 2017 update 5:
Traceback (most recent call last):
 File "C:\Maya_configs\FabisModule\scripts\salient_menu.py", line 183, in do_select
self.update_visualization()
 File "C:\Maya_configs\FabisModule\scripts\salient_menu.py", line 237, in update_visualization
   ys = [self.get_error(n, normalized=True) for n in range(min_keyframes, max_keyframes + 1)]
  File "C:\Maya_configs\FabisModule\scripts\salient_menu.py", line 220, in get_error
    return self.selections[n]["error"] / self.selections[min_n]["error"]
 ZeroDivisionError: float division by zero

Maya 2018.4:
 Traceback (most recent call last):
   File "C:\Maya_configs\FabisModule\scripts\salient_menu.py", line 183, in do_select
     self.update_visualization()
   File "C:\Maya_configs\FabisModule\scripts\salient_menu.py", line 237, in update_visualization
     ys = [self.get_error(n, normalized=True) for n in range(min_keyframes, max_keyframes + 1)]
   File "C:\Maya_configs\FabisModule\scripts\salient_menu.py", line 220, in get_error
     return self.selections[n]["error"] / self.selections[min_n]["error"]
 ZeroDivisionError: float division by zero

I'm using SalientPoses_Windows_Maya2017.zip and SalientPoses_Windows_Maya2018.zip which I get from release page.

**Comment by richard-roberts** [comment]
Hi there, thanks for posting this issue. And sorry that this didn't work first time for you :(

This happens when the `salientSelect` command fails, which is executed as part of the evaluation process. This means that no results are returned (aka zero result), and hence the error you've got. I should add a check for this so that the menu reports the issue - sorry!

The most likely cause for the failure is that the plugin file (`.so` on Linux, `.bundle` on OSX, and `.mll` on Windows) cannot find the OpenCL program (the file named `kernel.cl`). As a first check, please ensure that `kernel.cl` is in the same directory as the plugin file. Can you let me know if doing that fixes this issue?

**Comment by Onefabis** [comment]
Wow, what a quick responce, Gosh, I really forgot to place kernel.cl next to mll. Now it worsks great. Thank you!!! :)
